### ISSUE TITLE
Emergency service tracking issue

### ISSUE THREAD

**Issue by FoseFx** [helpwave/services#11]
> Users can create a new emergency and then answer questions. Finally they get see a list of appropriate ERs and can register their emergency with it. Admins can add these questions along with their respective answers.

> On a technical level this means we have to expose an endpoint with all Questions and Possible answers for the app to request. Another endpoint can then update the current emergency (probably event driven).

https://wiki.helpwave.de/doc/services-LSQieyjN8R

### TODOs:
* [x] #12
* [x] #13
* [x] #14
* [x] #15
* [x] #16
* [x] #17
* [ ] Move [Trello Card](https://trello.com/c/d1LLlRIS/28-emergency-service)

**Comment by MaxSchaefer** [comment]
We do not currently need the `emergency-room-svc` and by the time we do, the requirements will have changed. Closed.
