### ISSUE TITLE
Check and implement methods for room service

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#147]
This [pull request](https://github.com/helpwave/services/pull/136) introduces essential changes on our `room-svc`. Check and implement missing methods.

Documentation: https://proto.helpwave.de/#proto%2fservices%2ftask_svc%2fv1%2froom_svc.proto

```[tasklist]
### Endpoints
- [x] [CreateRoom](https://github.com/helpwave/services/blob/main/proto/services/task_svc/v1/room_svc.proto#L112)
- [x] [GetRoom](https://github.com/helpwave/services/blob/main/proto/services/task_svc/v1/room_svc.proto#L113)
- [x] [GetRooms](https://github.com/helpwave/services/blob/main/proto/services/task_svc/v1/room_svc.proto#L114)
- [x] [GetRoomsByWard](https://github.com/helpwave/services/blob/main/proto/services/task_svc/v1/room_svc.proto#L115)
- [x] [UpdateRoom](https://github.com/helpwave/services/blob/main/proto/services/task_svc/v1/room_svc.proto#L116)
- [x] [DeleteRoom](https://github.com/helpwave/services/blob/main/proto/services/task_svc/v1/room_svc.proto#LL117C7-L117C17)
```

**Comment by shivadharmi** [comment]
@MaxSchaefer Do we have any schema documents for entities?

**Comment by MaxSchaefer** [comment]
> @MaxSchaefer Do we have any schema documents for entities?

What do you mean with "schema documents" (documentations)? The schema for a room is [defined here](https://github.com/helpwave/services/blob/main/services/task-svc/internal/room/models/models.go#L9).

**Comment by shivadharmi** [comment]
@MaxSchaefer GetRoomResponse has an extra fields that are not defined in the struct and also new migration need to be added to update db with new fields. https://github.com/helpwave/services/blob/83af58a62c3b57bbcc233f4545f2b08eb2e047fa/proto/services/task_svc/v1/room_svc.proto#L28

**Comment by MaxSchaefer** [comment]
> @MaxSchaefer GetRoomResponse has an extra fields that are not defined in the struct and also new migration need to be added to update db with new fields. https://github.com/helpwave/services/blob/83af58a62c3b57bbcc233f4545f2b08eb2e047fa/proto/services/task_svc/v1/room_svc.proto#L28

Sounds good. Thats the point of this issue to implement new schemas and methods as needed by the proto definition.

**Comment by shivadharmi** [comment]
@MaxSchaefer Is this correct ?
```go
Beds           []Bed     `gorm:"foreignKey:RoomID"`
```

**Struct Definitions:**
```go
type Room struct {
	Base
	ID             uuid.UUID `gorm:"column:id"`
	OrganizationID uuid.UUID `gorm:"column:organization_id"`
	Beds           []Bed     `gorm:"foreignKey:RoomID"`
	WardId         uuid.UUID `gorm:"column:ward_id"`
}
```
```go
type Bed struct {
	ID     uuid.UUID `gorm:"column:id"`
	RoomID uuid.UUID `gorm:"column:room_id"`
}
```

**Comment by MaxSchaefer** [comment]
@shivadharmi looks good. `Beds` can be in the `Rooms`-Entity to, on the database level, `Beds` is holding the ID of `Rooms`.

Take a look ad this https://github.com/helpwave/services/pull/136#issuecomment-1524112264 diagram.

**Comment by shivadharmi** [comment]
I making a draft PR. Please take a look and let me know if I need to any other changes.
