### ISSUE TITLE
Implement `Memberships`

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#158]
A relational diagram of the membership's entity can be found at https://github.com/helpwave/services/issues/149.

**Comment by DasProffi** [comment]
Should this replace the `Members` database or should this be used alongside it?

**Comment by MaxSchaefer** [comment]
> Should this replace the `Members` database or should this be used alongside it?

`Memberships` replaces `Members`. Make sure to leave the signature of [`AddUserToOrganization`](https://github.com/helpwave/services/blob/86ea6cf26f92d94da8e1bf4dbb055a578432a1b0/services/user-svc/internal/organization/organization.go#L244) untouched.

**Comment by DasProffi** [comment]
> > Should this replace the `Members` database or should this be used alongside it?
> 
> `Memberships` replaces `Members`. Make sure to leave the signature of [`AddUserToOrganization`](https://github.com/helpwave/services/blob/86ea6cf26f92d94da8e1bf4dbb055a578432a1b0/services/user-svc/internal/organization/organization.go#L244) untouched.

So we add a user inside that method and then change their admin status outside of it?

**Comment by MaxSchaefer** [comment]
> > > Should this replace the `Members` database or should this be used alongside it?
> > 
> > 
> > `Memberships` replaces `Members`. Make sure to leave the signature of [`AddUserToOrganization`](https://github.com/helpwave/services/blob/86ea6cf26f92d94da8e1bf4dbb055a578432a1b0/services/user-svc/internal/organization/organization.go#L244) untouched.
> 
> So we add a user inside that method and then change their admin status outside of it? That seems a bit unnecessary

See https://github.com/helpwave/services/pull/181/files#r1225919532
