### ISSUE TITLE
Task and SubTask protos: rename attribute `title` to `name`

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#172]
We should rename the descriptive attribute of our proto definitions for `Task` and `SubTask` to `name`.

**Comment by florian-sabonchi** [comment]
Hello, I would suggest that we name everything so that it is consistent. I have created a pull request for this

**Comment by MaxSchaefer** [comment]
@florian-sabonchi has brought to our attention that we should use `name` instead of `title` as the descriptor for `Task`and `TaskTemplate` because `name` is already used on https://github.com/helpwave/web and right now, `name` is also the descriptor for other entities as well.
