### ISSUE TITLE
rename Unpublish to UnPublish

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/services#176]
Unpublish should be UnPublish instead.

**Comment by use-to** [comment]
@florian-sabonchi Why? I don't really sense the idea of this issue. `unpublish` is a word. Would you write `deactivate` as `deActivate`? (That would be lower-camel-case)

**Comment by MaxSchaefer** [comment]
Was about to say the same. See https://dictionary.cambridge.org/dictionary/english/unpublished

**Comment by florian-sabonchi** [comment]
In principle you are right, but I got a hint that the spelling violates the convention of Go in GoLand.

**Comment by florian-sabonchi** [comment]
We can also leave it, then I close the PR as not planned
