### ISSUE TITLE
`CreateTaskTemplate`

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#201]
The goal of this issue is to create a new gRPC service called `task-template-svc` with the corresponding Protobuf for the `CreateTaskTemplate` method inside the `task-svc` microservice.

The model of a TaskTemplate is already defined in https://github.com/helpwave/services/issues/200. 

Here is an outline for the Protobuf
```protobuf
message CreateTaskRequest {
  string name = 1;
  string description = 2;
  bool public = 3;
  optional string ward_id = 4;
  optional SubTask subtasks = 5; // When passed, every subtask is a seperate entity

  message SubTask {
    string name = 1;
  }
}
```

**Comment by DasProffi** [comment]
The proto buf generation of this is missing, is this part of this issue and if so, should there a new service called template_svc or should this be fully integrated in the task_svc and the task-svc/internal/task?

**Comment by MaxSchaefer** [comment]
@DasProffi I've updated the issue.
What do you think, should we reuse the Subtasks Entity of the Tasks for the Task Templates as well?

**Comment by DasProffi** [comment]
> @DasProffi I've updated the issue. What do you think, should we reuse the Subtasks Entity of the Tasks for the Task Templates as well?

Yes, but not as the same object. We should create another class with exactly the same attrubutes so, if they are going to diverge its easy to apply the changes

**Comment by MaxSchaefer** [comment]
> > @DasProffi I've updated the issue. What do you think, should we reuse the Subtasks Entity of the Tasks for the Task Templates as well?
> 
> Yes, but not as the same object. We should create another class with exactly the same attrubutes so, if they are going to diverge its easy to apply the changes

Let's do this. We could name this entity `Subtask` as well because this entity will live in a new package. You could rename this with GORM https://gorm.io/docs/conventions.html#TableName.
