### ISSUE TITLE
GetWardDetails

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#230]
`GetWardDetailsRequest`
```json
{
  "id": string
}
```

`GetWardDetailsResponse` 
```json
{
  "id": string,
  "name": string,
  "rooms: [
    {
      "name": string,
      "beds": [
        {
          "id": string
        }
      ]
    }
  ],
  "task_templates": [
    {
      "id: string,
      "name": string,
      "subtasks": [
        {
          "id": string,
          "name": string
        }
      ]
    }
  ]
}
```

**Comment by MaxSchaefer** [comment]
@florian-sabonchi this issue is blocked by #203. When #203 is merged, you can start working on this issue.

**Comment by MaxSchaefer** [comment]
@florian-sabonchi this is ready. If you want, you can build on top of #237 in a new branch.

**Comment by florian-sabonchi** [comment]
> @florian-sabonchi this is ready. If you want, you can build on top of #237 in a new branch.

Sound googd thanks for information
