### ISSUE TITLE
Refactor directory structure of task-svc

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#238]
tbd

**Comment by DasProffi** [comment]
Currently models are saved in the `/task-svc/internal/<name of subservice>/models/models.go` which leads to an overly complicated folder and file structure, while not containing many files for example  `/task-svc/internal/<name of subservice>/` only has 3 three files with all subdirectories

Possible suggestions:
-  `/task-svc/models/<name of subservice>.go` for models and `/task-svc/repository/<name of subservice>.go` for helper repository functions
-  `/task-svc/internal/<name of subservice>/models.go`
