### ISSUE TITLE
go mod replacements breaks docker build

### ISSUE THREAD

**Issue by use-to** [helpwave/services#25]
### Describe the bug
The lib path replacements in `go.mod` will break the docker build cause these libs are out of dockers context. 

### Reproduce
`docker build services/user-svc/`

### Logs
```
Sending build context to Docker daemon  54.27kB
Step 1/15 : FROM golang:1.19 AS builder
 ---> 8827cedaa309
Step 2/15 : WORKDIR /app
 ---> Using cache
 ---> d763ff2635d0
Step 3/15 : COPY . /app
 ---> Using cache
 ---> 13d2a73edae4
Step 4/15 : ARG VERSION
 ---> Using cache
 ---> cba1e0088c93
Step 5/15 : RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-X main.Version=${VERSION}" -a -o app .
 ---> Running in b06857608dae
go: downloading golang.org/x/crypto v0.0.0-20220722155217-630584e8d5aa
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/dapr/go-sdk v1.6.0
go: downloading github.com/rs/zerolog v1.28.0
go: downloading github.com/mattn/go-colorable v0.1.12
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading golang.org/x/sys v0.0.0-20220520151302-bc2c85ada10a
main.go:4:2: common@v0.0.0: replacement directory ../../libs/common does not exist
main.go:9:2: hwgorm@v0.0.0: replacement directory ../../libs/hwgorm does not exist
main.go:10:2: hwutil@v0.0.0: replacement directory ../../libs/hwutil does not exist
main.go:11:2: logging@v0.0.0: replacement directory ../../libs/logging does not exist
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -ldflags="-X main.Version=${VERSION}" -a -o app .' returned a non-zero code: 1
```

### Additional Comments
We have to restructure the project so that docker can use that shared lib directory!

**Comment by use-to** [comment]
Possible solution: Move all Dockerfiles to the root directory and name them like this: `Dockerfile.user`
So we can add the `libs` directory to the intermediate build container without a problem! 🦖

**Comment by FoseFx** [comment]
we can use the Dockerfiles of a service from the root context as well, maybe wrap it in a Makefile? `make docker <svc>` would then call `docker build -f services/<svc>/Dockerfile` (COPYs and so on need to change I guess)

**Comment by MaxSchaefer** [comment]
> we can use the Dockerfiles of a service from the root context as well, maybe wrap it in a Makefile? `make docker <svc>` would then call `docker build -f services/<svc>/Dockerfile .` (COPYs and so on need to change I guess)

@FoseFx good idea but same result.

When we get rid of _replace_ in our go.mod files and name our packages correctly[1], we can require the packages in our go mod file via GitHub instead of replace. This should also fix the docker build. But then, every developer needs to _replace_ packages manually when they need to modify these.

**Comment by FoseFx** [comment]
But this means we will rely on the latest `main` as the source of truth for our libraries, right?
Does this also mean we have to update the hashes of all dependents of the libraries when we make a change?
Another problem I see is with API changes in a lib. We need to push it to main, before we can use it in a service correct? Breaking changes are pretty much impossible then.
