### ISSUE TITLE
Don't pass every error to the client

### ISSUE THREAD

**Issue by FoseFx** [helpwave/services#28]
### Is your feature request related to a problem? Please describe:
For what I can see the dapr SDK simply responds with  `err.Error()` in case we return an error.
As the content type is `text/plain` we limit ourselves in the richness of errors we can provide.
We can not add translations or additional error codes or alike.

### Describe the solution you'd like
Return a simple json object.
```json
{
  "error": {
    "message": "..."
  }
}
```
We can extend it later if we need to.

### Additional Comments
We should also update the content-type header to `application/json` and probably need to write middleware for this.

**Comment by MaxSchaefer** [comment]
We are moved to gRPC, but still our errors are quite "transparent".
