### ISSUE TITLE
GetOrganizationsByUser returns Organization twice

### ISSUE THREAD

**Issue by DasProffi** [helpwave/services#320]
### Describe the bug

GetOrganizationsByUser returns Organization twice

### Describe how to produce the bug

request GetOrganizationsByUser

### Additional context

From https://github.com/helpwave/web/issues/535
Also tried to fix in #307

**Comment by DasProffi** [comment]
@MaxSchaefer could you look at the database and make sure that our is only a member once in the organisation with the id "192bac96-88a8-42a4-a9ea-adca168607f4". In that case we might want to ensure that this isn't possible or entirely remove the id on the membership?

@FoseFx you might also look into it if you have db access

**Comment by FoseFx** [comment]
id                  |       long_name        |    short_name      | is_personal |          created_by_user_id          
-----------------|---------------------------|-------------------------|-----------------|------------------------------------------
192bac96-88a8-42a4-a9ea-adca168607f4 | Uniklinikum Münster    | UKM              |  f           | 18159713-5d4e-4ad5-94ad-fbb6bb147984
37e5e037-7acf-4d39-80c0-cc2a0903a4c4 | Uniklinikum Münster    | UKM              |  f           | 18159713-5d4e-4ad5-94ad-fbb6bb147984

**Comment by MaxSchaefer** [comment]
@FoseFx can we use a composite key for this on the memberships table?
