### ISSUE TITLE
`soft_delete.DeletedAt` instead of `int`

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#329]
Why did you use an int over a boolean? Rather make it a bool or enum, if the gorm soft_delete doesn't work and make sure that all gets and updates are still returning only not discharged patients
@MaxSchaefer do you have a good solution to this?

_Originally posted by @DasProffi in https://github.com/helpwave/services/pull/325#discussion_r1278295954_

## To-do

- Are there any issues with `soft_delete.DeletedAt`? @florianjs 
- Migrate back to `soft_delete.DeletedAt`

**Comment by DasProffi** [comment]
@MaxSchaefer what is this issue about, the deleted_at should be correct as the type? Or did this cause issues with the db?

**Comment by MaxSchaefer** [comment]
> @MaxSchaefer what is this issue about, the deleted_at should be correct as the type? Or did this cause issues with the db?

I've updated the issue.
> ## To-do
>
> - Are there any issues with `soft_delete.DeletedAt`? @florianjs 
> - Migrate back to `soft_delete.DeletedAt`

**Comment by DasProffi** [comment]
@MaxSchaefer it was reverted back to softdelete in the pr see
https://github.com/helpwave/services/blob/0bb3fe102b164b21eec3b4a438bbdb1bdcb5ed4a/services/task-svc/internal/patient/models/models.go#L20

**Comment by MaxSchaefer** [comment]
> @MaxSchaefer it was reverted back to softdelete in the pr see
> 
> https://github.com/helpwave/services/blob/0bb3fe102b164b21eec3b4a438bbdb1bdcb5ed4a/services/task-svc/internal/patient/models/models.go#L20

Oh, yeah. You are right. I got confused by the late review on my side of #325 sorry :)
