### ISSUE TITLE
PatientDelete

### ISSUE THREAD

**Issue by DasProffi** [helpwave/services#330]
### Describe the feature

Delete Patient request only using the patient id

### Why is this feature needed?

because we use soft deletes from gorm, but we also need the function to delete all patient information

**Comment by DasProffi** [comment]
@MaxSchaefer i dont know whether we want to establish any safty restrictions here, that a patient has to be discharged before deleting

**Comment by MaxSchaefer** [comment]
> because we use soft deletes from gorm, but we also need the function to delete all patient information

Sounds like a GDPR-compliant delete. An `isAdmin`-check should be enough for now. Before that, we need another endpoint to load soft deleted patients and a custom UI for that. We need to discuss this first. This endpoint can still be implemented, including the admin check.

**Comment by DasProffi** [comment]
We have this delete feature already in the patient list showing all discharged patients with a delete button afterward
