### ISSUE TITLE
Implement an internal abstraction for recent entities

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#335]
The goal is to have an internal abstraction / function / service available to publish keys with a lifetime X into our redis that holds Y amount of identifiers for a group of entities. The map should also keep a maximum of Z identifiers (Ring Buffer, First-In First-Out).

Example
```
addRecentEntity('wards', userId, wardId); // appends the wardId to a map that is scoped to a user
getRecentEntities('wards', userId) // returns the recent wardIds for a user
```

**Comment by FoseFx** [comment]
The lifetime should be a property of the whole key (e.g. `wards-userabcd`) right? (vs: every item in a map has a lifetime) I assume it resets with every write as well?

**Comment by FoseFx** [comment]
If so, I propose the use of [sorted sets](https://redis.io/docs/data-types/sorted-sets/), where the score is the write timestamp.
`addRecentEntity('wards', userId, wardId)` will issue two redis commands:
`ZADD wards-{userid} {unixtime} {wardId}` and
`EXPIRE  wards-{userid} {some preconfigured amount of seconds}`

and `getRecentEntities('wards', userId)` becomes
`ZRANGE wards-{userid} 0 -1`

**Comment by MaxSchaefer** [comment]
Sounds good. Why should the `ZADD` + `EXPIRE` creates garbage?
> [After the timeout has expired, the key will automatically be deleted.](https://redis.io/commands/expire/)

**Comment by FoseFx** [comment]
As long as the key does not expire, the set will always grow, even though we only ever query the top Z items.
