### ISSUE TITLE
Track recent patients per user

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#367]
With #365 in place, we can build up a record of recent patients per user.

Every following method triggers a recent interaction with a patient
- `CreatePatient`
- `UpdatePatient`
- `GetPatientDetails`

Every following method should remove the patient from the LRU 
- `DischargePatient`
- `DeletePatient`

**Comment by MaxSchaefer** [comment]
@FoseFx low hanging would be to populate the LRU in every method. Could you research a more generic approach?

**Comment by FoseFx** [comment]
I don't think `DischargePatient` should remove it from the LRU. I can imagine it is useful to have swift access to a patient, if just discharged them by accident.
I'll implement if for now, maybe talk this over with medical

**Comment by FoseFx** [comment]
Also keep in mind, that `RemoveItemForUser` does not cross user boundaries, so only the user, that discharged/removed the patient will get them cleared of their recent activity.
