### ISSUE TITLE
Deleting a ward doesnt unassign Bed

### ISSUE THREAD

**Issue by DasProffi** [helpwave/services#372]
### Describe the bug

Deleting a ward doesn't unassign a Bed from a Patient

### Describe how to produce the bug

1. Assign a patient to a bed
2. Delete the ward of the bed
3. fetch the PatientList

The patient still has the bed assigned to them, although the bed doesn't exist anymore

**Comment by MaxSchaefer** [comment]
@FoseFx could you take a look into that bug?

**Comment by florianjs** [comment]
> [ward_id is not a FK and does not cascade](https://github.com/helpwave/services/blob/833c6355905f2dbca9754fc825b79574111d2bf0/services/task-svc/migrations/000007_room_ward_id.up.sql#L2)
> 
> I'm on it

THKs
