### ISSUE TITLE
Reactivate discharged patients

### ISSUE THREAD

**Issue by DasProffi** [helpwave/services#397]
### Describe the feature

Reactivate discharged patients by removing the soft delete flag

### Why is this feature needed?

Discharged patients still exist, but can't be used anymore, thus a reactivation would required

### Additional context
```proto
//
// ReactivatePatient
//

message ReactivatePatientRequest {
  string id = 1; // @gotags: validate:"uuid4"
}

message ReactivatePatientResponse {}
```

Note: You will need to use the `db.Unscoped().<query>` to be able to interact with soft deleted patients

**Comment by DasProffi** [comment]
@MaxSchaefer What would you prefer as the semantics?

Do we want to throw an error if the discharged patient already is active (not discharged) or is that okay?

**Comment by MaxSchaefer** [comment]
> @MaxSchaefer What would you prefer as the semantics?
> 
> Do we want to throw an error if the discharged patient already is active (not discharged) or is that okay?

The endpoint should be idempotent. A consecutive call to that endpoint should return the same as the first call. Don't throw an error when a patient is already active again.
