### ISSUE TITLE
GetPatient for discharged patients

### ISSUE THREAD

**Issue by DasProffi** [helpwave/services#475]
### Describe the feature

GetPatient should have some way of returning discharged patient information and not just not discharged patients.

This can be done by adding Unscoped() in front of the query

### Why is this feature needed?

So the frontend can fetch discharged patients and show their information

### Additional context

From https://github.com/helpwave/web/issues/689

**Comment by Dominik26-1** [comment]
Hi, I would like to contribute to this issue, can you assign to me?

**Comment by DasProffi** [comment]
> Hi, I would like to contribute to this issue, can you assign to me?

Yes, there you go ^^

**Comment by MaxSchaefer** [comment]
@Dominik26-1 any progress on this?
