### ISSUE TITLE
GetTasksForUser

### ISSUE THREAD

**Issue by DasProffi** [helpwave/services#486]
### Describe the feature

`GetTasksForUser` should return a List of all tasks assigned to the current user.

The tasks should hold all task attributes and the patient with id and name

### Why is this feature needed?

Mobile needs this

**Comment by MaxSchaefer** [comment]
@DasProffi same schema as `GetTasksByPatientResponse`?
@PaulKalho good issue for you?

**Comment by DasProffi** [comment]
> @DasProffi same schema as `GetTasksByPatientResponse`?
Same as `GetTaskResponse` but repeated

**Comment by PaulKalho** [comment]
> @PaulKalho good issue for you?

yes, will assign myself asap

**Comment by PaulKalho** [comment]
@DasProffi what is the difference to `GetAssignedTasks` ?

**Comment by DasProffi** [comment]
> @DasProffi what is the difference to `GetAssignedTasks` ?

None, if the proto schema is the same and the endpoint is implemented you can close this

**Comment by PaulKalho** [comment]
> > @DasProffi what is the difference to `GetAssignedTasks` ?
> 
> None, if the proto schema is the same and the endpoint is implemented you can close this

Actually  `GetAssignedTasks` is missing the `organization_id` as well as `status` of a task, should I add them?

**Comment by DasProffi** [comment]
> > > @DasProffi what is the difference to `GetAssignedTasks` ?
> > 
> > None, if the proto schema is the same and the endpoint is implemented you can close this
> 
> Actually  `GetAssignedTasks` is missing the `organization_id` as well as `status` of a task, should I add them? 

Only the status, we currently don't need the organization id
