### ISSUE TITLE
GetPatientListRequest return tasks and notes

### ISSUE THREAD

**Issue by DasProffi** [helpwave/services#488]
### Describe the feature

The get patient list request should return the tasks and notes for the patient to have full information

### Why is this feature needed?

To display the TaskStatuses properly in mobile

### Additional context

From https://github.com/helpwave/mobile-app/issues/418

**Comment by PaulKalho** [comment]
should it just return the count for each task-status like in `getWardOverview` or the complete task with all its details?

**Comment by DasProffi** [comment]
> should it just return the count for each task-status like in `getWardOverview` or the complete task with all its details?

The count for each status is sufficient for now, but could also be implemented by providing a list of all tasks
