### ISSUE TITLE
Discourage commits through CI

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#591]
### Describe the bug

Our CI fails due to the lack of commit permissions to main. `GITHUB_TOKEN` cannot bypass branch-protections and for some reasons `HELPWAVE_BOT_PAT` was also not working. We can either fiddle around with the permission or get entirely rid of re-commits in our CI. For me, re-commits generally feel very unstable and rather unclean ... _rant_.

Right now, we are using re-commits for storing and saving versions for our published packages. I am looking forward to get rid of generated code for packages that are not directly in use of this repository as well. This can be the first or only step the towards this.

- [ ] Packages that are not in direct use of this repository should not be inside this repository
- [ ] On proto changes, run the generation, pull versions and publish them

### Describe how to produce the bug

[_See CI_](https://github.com/helpwave/services/actions/runs/7315474342/job/19929164233)

**Comment by MaxSchaefer** [comment]
@FoseFx what do you think?

**Comment by FoseFx** [comment]
What's the alternative? At some point, the version commit has to be made. If not in this repo, then somewhere else.

**Comment by MaxSchaefer** [comment]
@FoseFx we should do something like https://github.com/Quantco/ui-actions/tree/main/publish - https://github.com/helpwave/web/blob/main/.github/workflows/publish.yaml.
- On gen/ changes -> Auto publish packages by fetch the current version from the registry.
- On a specific version change (for example package.json) -> Publish packages to the passed version.
- Never commit back to the repository

**Comment by MaxSchaefer** [comment]
@FoseFx any progress on this one? Quite urgent due to failing CI on main.

**Comment by FoseFx** [comment]
I wrote [this](https://github.com/helpwave/services/pull/598), but did not have the time to test it yet
