### ISSUE TITLE
AuthZ

### ISSUE THREAD

**Issue by FoseFx** [helpwave/services#61]
### Describe the solution you'd like
Setup Keycloak Authorization.

**Comment by MaxSchaefer** [comment]
To what degree does Keycloak handle our authorization? I see it more as part of the business logic.

**Comment by FoseFx** [comment]
The goal is to simply ask keycloak "Hey, is A allowed to modify the name of the organization B?"
For this to work we then set rules for who is allowed to modify organizations (admins of the org) and then let KC check if those conditions are met.

There are different ways to state these rules and I am still researching them. An alternative is sth. like [Open Policy Agent](https://www.openpolicyagent.org/)

**Comment by FoseFx** [comment]
There is somewhat of a science to this, but I think [this section](https://www.keycloak.org/docs/latest/authorization_services/index.html#_overview_architecture) of the docs gives a good overview.

**Comment by MaxSchaefer** [comment]
Closed due to our migration to ory.sh. Will also be further tracked by #149
