### ISSUE TITLE
Property-Service: Aggregate Design

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#611]
Based on https://github.com/helpwave/helpwave/issues/109#issuecomment-1891115038 and previous discussion, we are about to implement properties in an event sourcing fashion. Aggregates are an integral part of this architecture, we need to talk about the design and slicing of our aggregates for properties.

https://doodle.com/meeting/participate/id/dGw8PV5d

FYI: The MVP does not include property-sets. If the aggregate design is not easy extendable later on when the property-sets should be implemented, we need to discuss this.

**Comment by MaxSchaefer** [comment]
https://wiki.helpwave.de/doc/property-service-aggregate-design-LjnHkD9NY3

**Comment by MaxSchaefer** [comment]
We designed the following aggregates in our meeting yesterday.

### Property
```jsonc
{
  id: string,
  
  subjectId: string, // roomID, wardID, patientID
  subjectType: string, // patient
  
  fieldType: enum, // text, number, checkbox, date, dateTime, select
  
  name: string,
  description?: string,
  isArchived: bool,
  isSoftRequired: bool,
  
  priortyDisplayedAtSubjectIds: []string
  
  setId?: string,
  
  selectOptions?: {
    id: string,
    name: string,
    description?: string,
  }[],
}
```

### PropertyValue
```jsonc
{
  id: string,
  propertyId: string,
  value: interface{}, // lol any
}
```

### PropertySet
```json
{
  id: string,
  name: string,
}
```

### PropertyView: TODO
```jsonc
{
  id: string,
  sourceSubjectType: string,
  
  view: {
    type: enum, // Property, Set
    id: string,
  },
}
```

**Comment by MaxSchaefer** [comment]
I've update my To-do comment on https://github.com/helpwave/helpwave/issues/109#issuecomment-1919712778

> - The soft-required feature is "view-only" and should be configured for example on the ward level
I guess thats clear.

> - If a data-type provides the ability to pre-define options, the user should still be able self-create and add custom ones during property assignment
The new property option should be added an option to the property with a "custom"-Flag on `true`.

**Comment by FoseFx** [comment]
### Views (Still WIP):

We want to collect rules for property relevance: A rule maps matchers to filters.
All except one rule (the root) extend another rule. An extension SHOULD NOT be able to conflict its parent.
A filter can thus replace, extend or ignore a lower level filter. Specifics need to be discussed based on the data types of the filters.

When querying the relevant properties of a subject, various parameters are sent along. Based on these, the most specific matching rule is found, from there the linked list is walked back to produce a final set of filters.

That one is then used to query the properties.

We need to see if we can use existing libs and/or libraries

**Comment by FoseFx** [comment]
```
{
	rule_id: string,
	extends: string | null, /* another rule */

	/* Matchers */
	ward_id: string | null,
	patient_id: string | null,
	
	/* Filters */
	soft_required: bool | null, /* show all soft_required, don't show all soft_required, no-rule (parent might have one) */
	include: [string] | null /* add properties to always show */
	dont_include: [string] | null /* remove by parent included property from include list */
}

```

**Comment by MaxSchaefer** [comment]
https://helpwave.slack.com/archives/C044CK01MU4/p1707217296393129

**Comment by FoseFx** [comment]
Two more additions to the rules:

 * We need a table to map a (rule_id, property_id) to a boolean "is_soft_required" as soft required is a property of the view.
 * On the filter side we also add an "order_id" string. We will add a table that maps (order_id, property_id) to a priority double. This will be used to order the properties.
