### ISSUE TITLE
APISIX: use secret for admin user

### ISSUE THREAD

**Issue by FoseFx** [helpwave/services#68]
### Is your feature request related to a problem? Please describe:
We deploy APISIX with the default credentials admin/admin.

### Describe the solution you'd like
Use a kubernetes secret.

**Comment by MaxSchaefer** [comment]
> Since the current Admin API is based on the etcd configuration center solution, enable Admin API is not allowed when the Stand-alone mode is enabled.
https://apisix.apache.org/docs/apisix/deployment-modes/#standalone

We are moved APISIX to standalone mode. The admin API is not active.
