### ISSUE TITLE
Dart protos not generated

### ISSUE THREAD

**Issue by DasProffi** [helpwave/services#698]
### Describe the bug

https://github.com/helpwave/services/tree/main/gen/dart/proto/services/task_svc/v1 only contains one file

### Describe how to produce the bug

Download the protos

**Comment by MaxSchaefer** [comment]
The generated libraries are getting generated just-in-time in our CI before getting published to the registries. Therefore the current `gen/` doesent represent the current published state (potential to remove `gen/` libs that are not required by `services`?).

Beside that, I've downloaded the lastest version from https://pub.dev/packages/helpwave_proto_dart/versions and yes, It contains just one file. @FoseFx can you give this a look?

**Comment by FoseFx** [comment]
You moved the directory in [this commit](https://github.com/helpwave/services/commit/4f08703086b13ba3c3b639799bdbb975a8218e28). All the files are here: https://github.com/helpwave/services/tree/main/gen/dart/lib/proto/services/task_svc/v1

**Comment by FoseFx** [comment]
I assume having files laying around *next* to the lib directory causes issues here, we'll see (#700).

**Comment by DasProffi** [comment]
> I assume having files lying around _next_ to the lib directory causes issues here, we'll see (#700).

In the downloaded package (version 0.37+) there exists no lib folder anymore which is probably the root cause for this, but we should also delete the files not within the lib folder as these are not registered anyway.

**Comment by FoseFx** [comment]
```
Package validation found the following potential issues:
* 78 checked-in files are ignored by a `.gitignore`.
  Previous versions of Pub would include those in the published package.
  
  Consider adjusting your `.gitignore` files to not ignore those files, and if you do not wish to
  publish these files use `.pubignore`. See also dart.dev/go/pubignore
  
  Files that are checked in while gitignored:
  
  lib/google/protobuf/any.pb.dart
  lib/google/protobuf/any.pbenum.dart
  lib/google/protobuf/any.pbjson.dart
  lib/google/protobuf/empty.pb.dart
  lib/google/protobuf/empty.pbenum.dart
  lib/google/protobuf/empty.pbjson.dart
  lib/google/protobuf/timestamp.pb.dart
  lib/google/protobuf/timestamp.pbenum.dart
  lib/google/protobuf/timestamp.pbjson.dart
  lib/proto/libs/events/v1/organization_events.pb.dart
 ```
???
