### ISSUE TITLE
Evaluate Stand-alone mode

### ISSUE THREAD

**Issue by FoseFx** [helpwave/services#70]
### Is your feature request related to a problem? Please describe:
APISIX can run in [stand-alone mode](https://apisix.apache.org/blog/2023/02/09/secure-apisix-admin/#standalone-mode).
The docs mention this removes the need for an etcd cluster.

### Describe the solution you'd like
Pro/cons of this.

**Comment by MaxSchaefer** [comment]
Stand-alone looks good. We configure everything inside a YAML and enable this mode via an env.
