### ISSUE TITLE
Let GetUserID and GetOrganizationID panic

### ISSUE THREAD

**Issue by FoseFx** [helpwave/services#811]
### Describe the chore

Currently, common's GetUserID and GetOrganizationID may return an error, if (and only if) the corresponding values were not attached to the context by the authFunc and handleOrganizationIDForAuthFunc middlewares.

For user-ids this can only happen, when either the service was not Setup() with enabled auth, or a route handler is in skipAuthForMethods, and yet called GetUserID. Either way, this is not an expected runtime error, instead indicates a programming mistake. It makes little sense to **always** handle these. I assume the grpc library will catch the panic and return an error, but we should check this first / implement this anyway.

For organization ids we currently have possible client error to attribute a missing id to. But this will change soon, when we start using jwt-claims for org ids. And as we currently deploy with a fallback org set, this will never error.

Both functions are currently used ~60 times, with error handling this removes at least 180 loc. And likely a lot more, as other functions may only error due to their usage of either one of those functions.

In general: user-error / environment-error -> error, invalid state -> panic

We should prefix them to `Must`, to indicate a possible panic to developers, which should make sure this function makes sense to call in their current context.

**Comment by FoseFx** [comment]
Blocked by #832

**Comment by MaxSchaefer** [comment]
Same for https://github.com/helpwave/services/pull/859#discussion_r1808924731
