### ISSUE TITLE
AttachPropertyValue only with set Value

### ISSUE THREAD

**Issue by DasProffi** [helpwave/services#838]
### Describe the bug

The AttachPropertyValue can only set a property value to an existing value and does not allow the addition of an undefined property value

### Describe how to produce the bug

1. Use attach property, but don't provide a value for any field type
2. The property isn't added.

**Comment by FoseFx** [comment]
undefined is encoded by the lack of a value, i'm not quite sure what you are trying to do here

As a reminder of the semantics:

A Property is a field that can be, but does not have to be set for a Subject. Think of it as a "key" in a key-value store.
A Property Value is the Value set for a Property on a Subject. Think of this as the value in a k/v store.

**Comment by FoseFx** [comment]
Not providing any value to AttachPropertyValue will attempt to remove any set value, that's why it works in that case.

**Comment by DasProffi** [comment]
> Not providing any value to AttachPropertyValue will attempt to remove any set value, that's why it works in that case.

Exactly, this enforces having to set default values in the frontend when adding a PropertyValue, as setting no PropertyValue (value == undefined) for the given field type results in the deletion of the AttachedPropertyValue on the subject.

**Comment by FoseFx** [comment]
> Exactly, this enforces having to set default values in the frontend when adding a PropertyValue, as setting no PropertyValue (value == undefined) for the given field type results in the deletion of the AttachedPropertyValue on the subject.

If there is no value to attach, simply don't try to attach any values.

> Frontends should be able to tell when a property value is set or not set when it is attached. 

When a value is attached, there is a value. I don't think I understand what you are saying here.

> The current implementation enforces these values to always be set to be obtained by queries like GetAttachedPropertyValuesRequest.

Why would you want to attach the value that you know is already attached again?

> Besides that, it is very counterintuitive to have an endpoint AttachProperty which signifies an "Upsert" operation to also include a delete.

The empty value is a value like any other! It happens that we internally represent it by removing some rows in tables.
In that way the attach endpoint is not an upsert, but simply an update. There is no  "inserting" a value, by default there always is a value: the empty value.

---

You are writing the empty value to a field, then why are you confused why the value is empty?

**Comment by DasProffi** [comment]
> You are writing the empty value to a field, then why are you confused why the value is empty?

Maybe I should expand my example for frontend intended behavior:
1. I have a property called age which is a number
2. The user attaches this property to a subject "patient1", without setting an age just to show that this property should be used for this subject
3. Then later a second user who sees this undefined value for the patient1 sets an age of 21

The 2. step is not supported as the backend only returns attached values which have a non-null value. This makes it impossible to have a set of properties shown for a certain subject with undefined values. See the screenshot below for the UI, it would be a very weird UX to first select a property on add and then have it disappear when no value was set.
![Frame 72](https://github.com/user-attachments/assets/5db9a1a7-6c6c-4326-b071-0232140dc86d)
