### ISSUE TITLE
Dart Protos  package does not have libs directory

### ISSUE THREAD

**Issue by DasProffi** [helpwave/services#844]
### Describe the bug

The generated Protos for dart don't include libs directory with `common/v1` and `events/v1` which produces errors on the normal tasks endpoints

### Describe how to produce the bug

1. Import the current helpwave proto package from pub.dev
2. use the tasks_service
3. Build fails with file not found

From `helpwave_proto_dart-0.51.0-dcc524f/lib/services/tasks_svc/v1/patient_svc.pb.dart:16:8:`
`Error when reading '.../helpwave_proto_dart-0.51.0-dcc524f/lib/libs/common/v1/conflict.pb.dart'`

**Comment by FoseFx** [comment]
Can you provide a (minimal) reproducer snippet / gist?
