### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by FoseFx** [helpwave/services#877]
PropertyService (#812)
- [x] CreateProperty
- [x] GetProperty
- [x] UpdateProperty
- [x] GetProperties

PropertySetService (#880)
- [x] CreatePropertySet
- [x] GetPropertySet

PropertyValueService (#885)
- [x] AttachPropertyValue
- [x] GetAttachedPropertyValues

PropertyViewsService (#885)
- [x] UpdatePropertyViewRule

BedService (#880)
- [x] CreateBed
- [x] GetBed
- [x] GetBeds
- [x] GetBedsByRoom
- [x] GetBedByPatient
- [x] UpdateBed
- [x] DeleteBed

PatientService (#882)
- [x] CreatePatient
- [x] GetPatient
- [x] GetPatientByBed
- [x] GetPatientsByWard
- [x] GetPatientAssignmentByWard
- [x] GetPatientDetails
- [x] GetPatientList
- [x] GetRecentPatients
- [x] UpdatePatient
- [x] AssignBed
- [x] UnassignBed
- [x] DischargePatient
- [x] ReadmitPatient
- [x] DeletePatient

RoomService (#880)
- [x] CreateRoom
- [x] GetRoom
- [x] GetRooms
- [x] UpdateRoom
- [x] DeleteRoom
- [x] GetRoomOverviewsByWard

TaskService (#882)
- [x] CreateTask
- [x] UpdateTask
- [x] GetTask
- [x] GetTasksByPatient
- [x] GetTasksByPatientSortedByStatus
- [x] GetAssignedTasks
- [x] AssignTask
- [x] UnassignTask
- [x] CreateSubtask
- [x] UpdateSubtask
- [x] DeleteSubtask
- [x] RemoveTaskDueDate
- [x] DeleteTask

TaskTemplateService (#885)
- [x] CreateTaskTemplate
- [x] DeleteTaskTemplate
- [x] DeleteTaskTemplateSubTask
- [x] UpdateTaskTemplate
- [x] UpdateTaskTemplateSubTask
- [x] CreateTaskTemplateSubTask
- [x] GetAllTaskTemplates
- [x] GetTaskTemplate

WardService (#880)
- [x] CreateWard
- [x] GetWard
- [x] GetWards
- [x] GetRecentWards
- [x] UpdateWard
- [x] DeleteWard
- [x] GetWardDetails
- [x] GetWardOverviews

OrganizationService
- [x] CreateOrganization
- [x] GetOrganization
- [x] GetOrganizationsByUser
- [x] GetOrganizationsForUser
- [x] UpdateOrganization
- [x] DeleteOrganization
- [x] GetMembersByOrganization
- [x] AddMember
- [x] RemoveMember
- [x] InviteMember
- [x] GetInvitationsByOrganization
- [x] GetInvitationsByUser
- [x] AcceptInvitation
- [x] DeclineInvitation
- [x] RevokeInvitation
- [x] CreatePersonalOrganization

UserService
- [x] CreateUser
- [x] ReadSelf
- [x] ReadPublicProfile
- [x] UpdateUser

Meta
- [x] (Cascade) Delete from Permissions Graph
- [x] Migrate Existing Postgres Relationships to Spice

**Comment by FoseFx** [comment]
TODO: delete from perm graph

**Comment by felixevers** [comment]
34/85 endpoints remaining
